[04/Jun/2017 21:01:57] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /PlayGame/
[04/Jun/2017 21:08:33] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /PlayGame/
[04/Jun/2017 21:09:25] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /PlayGame/
[04/Jun/2017 21:09:52] WARNING [django.request:170] Not Found: /favicon.ico
[04/Jun/2017 21:10:20] ERROR [django.request:256] Internal Server Error: /GameDetails/results/994/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 451, in game_results
    games=Game.objects.get(id=game)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\db\models\query.py", line 334, in get
    self.model._meta.object_name
pricingsimulation.models.DoesNotExist: Game matching query does not exist.
[04/Jun/2017 21:10:56] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /Dashboard/
[04/Jun/2017 21:11:00] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /Dashboard/
[04/Jun/2017 21:18:25] WARNING [django.request:170] Not Found: /favicon.ico
[04/Jun/2017 21:18:38] WARNING [django.request:170] Not Found: /favicon.ico
[04/Jun/2017 21:26:52] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /PlayGame/
[04/Jun/2017 21:32:17] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /PlayGame/
[04/Jun/2017 22:04:36] WARNING [django.request:170] Not Found: /favicon.ico
[04/Jun/2017 22:04:44] WARNING [django.request:170] Not Found: /favicon.ico
[04/Jun/2017 22:05:55] WARNING [django.request:170] Not Found: /favicon.ico
[04/Jun/2017 22:09:34] ERROR [django.request:256] Internal Server Error: /next_turn_update/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1236, in update_turn_notify
    if turn >= game_data.no_of_turns_per_player:
NameError: name 'turn' is not defined
[04/Jun/2017 22:09:40] ERROR [django.request:256] Internal Server Error: /next_turn_update/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1236, in update_turn_notify
    if turn >= game_data.no_of_turns_per_player:
NameError: name 'turn' is not defined
[04/Jun/2017 22:10:29] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /PlayGame/
[04/Jun/2017 22:13:58] ERROR [django.request:256] Internal Server Error: /next_turn_update/
Traceback (most recent call last):
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\utils.py", line 495, in update_Player_not_bidded
    UserGameRecords.objects.get(game_id=gameid, user_id=nb, no_of_turns_completed=turn)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\db\models\query.py", line 334, in get
    self.model._meta.object_name
pricingsimulation.models.DoesNotExist: UserGameRecords matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1235, in update_turn_notify
    calculate_formulas(game_id, my_turn)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\utils.py", line 157, in calculate_formulas
    update_Player_not_bidded(game_id, turn, get_game_data.no_of_turns_per_player)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\utils.py", line 506, in update_Player_not_bidded
    old_fleet = FleetNetContribution.objects.get(game_id=gameid, player_id=nb, no_of_turn=turn - 1)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\db\models\query.py", line 338, in get
    (self.model._meta.object_name, num)
pricingsimulation.models.MultipleObjectsReturned: get() returned more than one FleetNetContribution -- it returned 2!
[04/Jun/2017 22:18:46] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /PlayGame/
[04/Jun/2017 22:20:54] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[04/Jun/2017 22:24:28] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /PlayGame/
[04/Jun/2017 22:24:41] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /PlayGame/
[04/Jun/2017 22:34:13] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /PlayGame/
[04/Jun/2017 22:36:17] ERROR [django.request:256] Internal Server Error: /next_turn_update/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1240, in update_turn_notify
    calculate_fleet_size(my_turn+1, request.user.id, game_data)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\utils.py", line 579, in calculate_fleet_size
    pre_simulation = pre_simulation[0]
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\db\models\query.py", line 184, in __getitem__
    return self._result_cache[k]
IndexError: list index out of range
[04/Jun/2017 22:38:13] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:13] ERROR [django.request:256] Internal Server Error: /next_turn_update/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1235, in update_turn_notify
    calculate_formulas(game_id, my_turn)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\utils.py", line 124, in calculate_formulas
    update_simulation(game_id,turn,get_player_limit)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\utils.py", line 176, in update_simulation
    a2b_award_trucks = award_A2B(gameid,turn, total_no_players)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\utils.py", line 629, in award_A2B
    fleet_size = calculate_fleet_size(turn, i.player_id, game_table)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\utils.py", line 572, in calculate_fleet_size
    print(trun, " trun number")
NameError: name 'trun' is not defined
[04/Jun/2017 22:38:13] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:13] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:13] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:13] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:13] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:13] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:13] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:13] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:13] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:14] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:14] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:14] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:14] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:14] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:14] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:14] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:14] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:14] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:14] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:14] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:14] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:15] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:15] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:15] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:15] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:15] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:15] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:15] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:15] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:15] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:15] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:15] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:15] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:38:15] ERROR [django.request:256] Internal Server Error: /PlaceBid/
Traceback (most recent call last):
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m80773\Documents\projects\Pricing_Simulation\pricing\pricing\pricingsimulation\views.py", line 1008, in placeit_divturn_update
    return HttpResponse(json.dumps(data),content_type='application/json')
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m80773\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Game' is not JSON serializable
[04/Jun/2017 22:41:50] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /PlayGame/
[04/Jun/2017 22:46:41] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /PlayGame/
[04/Jun/2017 22:47:37] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /PlayGame/
[04/Jun/2017 23:18:50] WARNING [django.request:170] Not Found: /favicon.ico
[04/Jun/2017 23:20:53] WARNING [django.request:170] Not Found: /favicon.ico
[04/Jun/2017 23:24:34] WARNING [django.request:170] Not Found: /favicon.ico
[05/Jun/2017 10:14:08] WARNING [django.request:170] Not Found: /favicon.ico
[05/Feb/2021 15:27:09] WARNING [django.request:222] Not Found: /favicon.ico
[05/Feb/2021 15:27:14] INFO [pricingsimulation.views:42] None:1612564034 Begin User Authentication
[05/Feb/2021 15:27:15] INFO [pricingsimulation.views:61] 1znz1290bbrulse82j2yaw0jb3swtuas:1612564035 End User Authentication
[05/Feb/2021 15:29:19] ERROR [django.request:222] Internal Server Error: /Dashboard/
Traceback (most recent call last):
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\cache\__init__.py", line 50, in _create_cache
    backend_cls = import_string(backend)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'redis_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\mgunturx\Documents\Copy of pricing_simulation_verison1\pricing_simulation_verison1_localgit\pricingsimulation\views.py", line 206, in dashboard
    game_data = cache.get("GameDetails%s"%game_id) or Game.objects.get(id=game_id)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\cache\__init__.py", line 98, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\cache\__init__.py", line 79, in __getitem__
    cache = _create_cache(alias)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\cache\__init__.py", line 52, in _create_cache
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'redis_cache.RedisCache': No module named 'redis_cache'
[05/Feb/2021 15:29:19] ERROR [django.request:222] Internal Server Error: /Dashboard/
Traceback (most recent call last):
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\cache\__init__.py", line 50, in _create_cache
    backend_cls = import_string(backend)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'redis_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\mgunturx\Documents\Copy of pricing_simulation_verison1\pricing_simulation_verison1_localgit\pricingsimulation\views.py", line 206, in dashboard
    game_data = cache.get("GameDetails%s"%game_id) or Game.objects.get(id=game_id)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\cache\__init__.py", line 98, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\cache\__init__.py", line 79, in __getitem__
    cache = _create_cache(alias)
  File "C:\Users\mgunturx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\cache\__init__.py", line 52, in _create_cache
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'redis_cache.RedisCache': No module named 'redis_cache'
[05/Feb/2021 15:35:30] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 1
[05/Feb/2021 15:35:30] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 1 in 0 seconds
[05/Feb/2021 15:36:10] INFO [pricingsimulation.views:1255] Turn No. 1 Number of Players 1 
[05/Feb/2021 15:36:10] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:36:10] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 2
[05/Feb/2021 15:36:10] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 2 in 0 seconds
[05/Feb/2021 15:36:37] INFO [pricingsimulation.views:1255] Turn No. 2 Number of Players 1 
[05/Feb/2021 15:36:37] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:36:37] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 3
[05/Feb/2021 15:36:37] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 3 in 0 seconds
[05/Feb/2021 15:36:42] INFO [pricingsimulation.views:1255] Turn No. 3 Number of Players 1 
[05/Feb/2021 15:36:42] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:36:42] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 4
[05/Feb/2021 15:36:42] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 4 in 0 seconds
[05/Feb/2021 15:36:45] INFO [pricingsimulation.views:1255] Turn No. 4 Number of Players 1 
[05/Feb/2021 15:36:45] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:36:45] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 5
[05/Feb/2021 15:36:45] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 5 in 0 seconds
[05/Feb/2021 15:36:48] INFO [pricingsimulation.views:1255] Turn No. 5 Number of Players 1 
[05/Feb/2021 15:36:48] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:36:48] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 6
[05/Feb/2021 15:36:48] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 6 in 0 seconds
[05/Feb/2021 15:36:52] INFO [pricingsimulation.views:1255] Turn No. 6 Number of Players 1 
[05/Feb/2021 15:36:52] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:36:52] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 7
[05/Feb/2021 15:36:52] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 7 in 0 seconds
[05/Feb/2021 15:36:55] INFO [pricingsimulation.views:1255] Turn No. 7 Number of Players 1 
[05/Feb/2021 15:36:55] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:36:55] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 8
[05/Feb/2021 15:36:55] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 8 in 0 seconds
[05/Feb/2021 15:36:58] INFO [pricingsimulation.views:1255] Turn No. 8 Number of Players 1 
[05/Feb/2021 15:36:58] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:36:58] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 9
[05/Feb/2021 15:36:58] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 9 in 0 seconds
[05/Feb/2021 15:37:01] INFO [pricingsimulation.views:1255] Turn No. 9 Number of Players 1 
[05/Feb/2021 15:37:01] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:37:01] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 10
[05/Feb/2021 15:37:01] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 10 in 0 seconds
[05/Feb/2021 15:37:03] INFO [pricingsimulation.views:496] Results requested by maheshpy85@gmail.com at 05-02-2021 15:37:03
[05/Feb/2021 15:37:03] INFO [pricingsimulation.views:516] 1znz1290bbrulse82j2yaw0jb3swtuas:1612564623 Begin generating Result for game id: 1148
[05/Feb/2021 15:37:03] INFO [pricingsimulation.views:835] Results has been generated in 0.032001 sec for game_id: 1148
[05/Feb/2021 15:37:03] INFO [pricingsimulation.views:572] 1znz1290bbrulse82j2yaw0jb3swtuas:1612564623 Done generating results for game id: 1148 in 0.074000 ms
[05/Feb/2021 15:38:30] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 1
[05/Feb/2021 15:38:30] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 79, 1
[05/Feb/2021 15:38:30] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 80, 1
[05/Feb/2021 15:38:30] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 1 in 0 seconds
[05/Feb/2021 15:38:37] INFO [pricingsimulation.views:1255] Turn No. 1 Number of Players 3 
[05/Feb/2021 15:38:37] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:38:37] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 2
[05/Feb/2021 15:38:37] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 79, 2
[05/Feb/2021 15:38:37] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 80, 2
[05/Feb/2021 15:38:37] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 2 in 0 seconds
[05/Feb/2021 15:38:39] INFO [pricingsimulation.views:1255] Turn No. 2 Number of Players 3 
[05/Feb/2021 15:38:39] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:38:39] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 3
[05/Feb/2021 15:38:39] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 79, 3
[05/Feb/2021 15:38:39] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 80, 3
[05/Feb/2021 15:38:40] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 3 in 0 seconds
[05/Feb/2021 15:38:42] INFO [pricingsimulation.views:1255] Turn No. 3 Number of Players 3 
[05/Feb/2021 15:38:42] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:38:42] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 4
[05/Feb/2021 15:38:42] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 79, 4
[05/Feb/2021 15:38:42] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 80, 4
[05/Feb/2021 15:38:42] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 4 in 0 seconds
[05/Feb/2021 15:38:52] INFO [pricingsimulation.views:1255] Turn No. 4 Number of Players 3 
[05/Feb/2021 15:38:52] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:38:52] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 5
[05/Feb/2021 15:38:52] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 79, 5
[05/Feb/2021 15:38:52] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 80, 5
[05/Feb/2021 15:38:52] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 5 in 0 seconds
[05/Feb/2021 15:39:02] INFO [pricingsimulation.views:1255] Turn No. 5 Number of Players 3 
[05/Feb/2021 15:39:02] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:39:02] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 6
[05/Feb/2021 15:39:02] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 79, 6
[05/Feb/2021 15:39:02] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 80, 6
[05/Feb/2021 15:39:02] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 6 in 0 seconds
[05/Feb/2021 15:39:12] INFO [pricingsimulation.views:1255] Turn No. 6 Number of Players 3 
[05/Feb/2021 15:39:12] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:39:12] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 7
[05/Feb/2021 15:39:12] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 79, 7
[05/Feb/2021 15:39:12] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 80, 7
[05/Feb/2021 15:39:12] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 7 in 0 seconds
[05/Feb/2021 15:39:20] INFO [pricingsimulation.views:1255] Turn No. 7 Number of Players 3 
[05/Feb/2021 15:39:20] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:39:20] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 8
[05/Feb/2021 15:39:20] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 79, 8
[05/Feb/2021 15:39:20] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 80, 8
[05/Feb/2021 15:39:20] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 8 in 0 seconds
[05/Feb/2021 15:39:27] INFO [pricingsimulation.views:1255] Turn No. 8 Number of Players 3 
[05/Feb/2021 15:39:28] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:39:28] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 9
[05/Feb/2021 15:39:28] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 79, 9
[05/Feb/2021 15:39:28] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 80, 9
[05/Feb/2021 15:39:28] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 9 in 0 seconds
[05/Feb/2021 15:39:40] INFO [pricingsimulation.views:1255] Turn No. 9 Number of Players 3 
[05/Feb/2021 15:39:40] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:39:40] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 10
[05/Feb/2021 15:39:40] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 79, 10
[05/Feb/2021 15:39:40] INFO [pricingsimulation.utils:328] Adding AI Player 1149, 80, 10
[05/Feb/2021 15:39:40] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 10 in 0 seconds
[05/Feb/2021 15:39:42] INFO [pricingsimulation.views:496] Results requested by maheshpy85@gmail.com at 05-02-2021 15:39:42
[05/Feb/2021 15:39:42] INFO [pricingsimulation.views:516] 1znz1290bbrulse82j2yaw0jb3swtuas:1612564782 Begin generating Result for game id: 1149
[05/Feb/2021 15:39:42] INFO [pricingsimulation.views:835] Results has been generated in 0.029997 sec for game_id: 1149
[05/Feb/2021 15:39:42] INFO [pricingsimulation.views:572] 1znz1290bbrulse82j2yaw0jb3swtuas:1612564782 Done generating results for game id: 1149 in 0.153996 ms
[05/Feb/2021 15:47:28] INFO [pricingsimulation.views:42] None:1612565248 Begin User Authentication
[05/Feb/2021 15:47:29] INFO [pricingsimulation.views:61] 72cajad57m5bgrdsib1s6z01d2abmby3:1612565249 End User Authentication
[05/Feb/2021 15:48:50] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 1
[05/Feb/2021 15:48:50] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 79, 1
[05/Feb/2021 15:48:50] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 80, 1
[05/Feb/2021 15:48:50] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 81, 1
[05/Feb/2021 15:48:50] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 82, 1
[05/Feb/2021 15:48:50] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 83, 1
[05/Feb/2021 15:48:50] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 1 in 0 seconds
[05/Feb/2021 15:48:57] INFO [pricingsimulation.views:1255] Turn No. 1 Number of Players 6 
[05/Feb/2021 15:48:57] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:48:57] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 2
[05/Feb/2021 15:48:57] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 79, 2
[05/Feb/2021 15:48:57] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 80, 2
[05/Feb/2021 15:48:57] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 81, 2
[05/Feb/2021 15:48:57] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 82, 2
[05/Feb/2021 15:48:57] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 83, 2
[05/Feb/2021 15:48:57] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 2 in 0 seconds
[05/Feb/2021 15:48:59] INFO [pricingsimulation.views:1255] Turn No. 2 Number of Players 6 
[05/Feb/2021 15:48:59] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:48:59] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 3
[05/Feb/2021 15:48:59] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 79, 3
[05/Feb/2021 15:48:59] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 80, 3
[05/Feb/2021 15:48:59] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 81, 3
[05/Feb/2021 15:48:59] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 82, 3
[05/Feb/2021 15:48:59] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 83, 3
[05/Feb/2021 15:49:00] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 3 in 0 seconds
[05/Feb/2021 15:49:01] INFO [pricingsimulation.views:1255] Turn No. 3 Number of Players 6 
[05/Feb/2021 15:49:01] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:49:01] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 4
[05/Feb/2021 15:49:01] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 79, 4
[05/Feb/2021 15:49:01] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 80, 4
[05/Feb/2021 15:49:01] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 81, 4
[05/Feb/2021 15:49:01] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 82, 4
[05/Feb/2021 15:49:01] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 83, 4
[05/Feb/2021 15:49:01] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 4 in 0 seconds
[05/Feb/2021 15:49:03] INFO [pricingsimulation.views:1255] Turn No. 4 Number of Players 6 
[05/Feb/2021 15:49:03] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:49:03] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 5
[05/Feb/2021 15:49:03] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 79, 5
[05/Feb/2021 15:49:03] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 80, 5
[05/Feb/2021 15:49:03] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 81, 5
[05/Feb/2021 15:49:03] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 82, 5
[05/Feb/2021 15:49:03] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 83, 5
[05/Feb/2021 15:49:03] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 5 in 0 seconds
[05/Feb/2021 15:49:04] INFO [pricingsimulation.views:1255] Turn No. 5 Number of Players 6 
[05/Feb/2021 15:49:04] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:49:04] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 6
[05/Feb/2021 15:49:04] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 79, 6
[05/Feb/2021 15:49:04] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 80, 6
[05/Feb/2021 15:49:04] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 81, 6
[05/Feb/2021 15:49:04] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 82, 6
[05/Feb/2021 15:49:04] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 83, 6
[05/Feb/2021 15:49:04] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 6 in 0 seconds
[05/Feb/2021 15:49:06] INFO [pricingsimulation.views:1255] Turn No. 6 Number of Players 6 
[05/Feb/2021 15:49:06] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:49:06] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 7
[05/Feb/2021 15:49:06] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 79, 7
[05/Feb/2021 15:49:06] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 80, 7
[05/Feb/2021 15:49:06] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 81, 7
[05/Feb/2021 15:49:06] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 82, 7
[05/Feb/2021 15:49:06] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 83, 7
[05/Feb/2021 15:49:06] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 7 in 0 seconds
[05/Feb/2021 15:49:07] INFO [pricingsimulation.views:1255] Turn No. 7 Number of Players 6 
[05/Feb/2021 15:49:07] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:49:07] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 8
[05/Feb/2021 15:49:07] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 79, 8
[05/Feb/2021 15:49:07] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 80, 8
[05/Feb/2021 15:49:07] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 81, 8
[05/Feb/2021 15:49:07] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 82, 8
[05/Feb/2021 15:49:07] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 83, 8
[05/Feb/2021 15:49:08] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 8 in 0 seconds
[05/Feb/2021 15:49:09] INFO [pricingsimulation.views:1255] Turn No. 8 Number of Players 6 
[05/Feb/2021 15:49:09] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:49:09] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 9
[05/Feb/2021 15:49:09] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 79, 9
[05/Feb/2021 15:49:09] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 80, 9
[05/Feb/2021 15:49:09] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 81, 9
[05/Feb/2021 15:49:09] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 82, 9
[05/Feb/2021 15:49:09] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 83, 9
[05/Feb/2021 15:49:09] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 9 in 0 seconds
[05/Feb/2021 15:49:11] INFO [pricingsimulation.views:1255] Turn No. 9 Number of Players 6 
[05/Feb/2021 15:49:11] INFO [pricingsimulation.views:1258] Updating AI Players
[05/Feb/2021 15:49:11] INFO [pricingsimulation.utils:320] AI Players bidding started for the turn no. 10
[05/Feb/2021 15:49:11] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 79, 10
[05/Feb/2021 15:49:11] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 80, 10
[05/Feb/2021 15:49:11] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 81, 10
[05/Feb/2021 15:49:11] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 82, 10
[05/Feb/2021 15:49:11] INFO [pricingsimulation.utils:328] Adding AI Player 1150, 83, 10
[05/Feb/2021 15:49:11] INFO [pricingsimulation.utils:382] AI Players bidding completed for turn no. 10 in 0 seconds
[05/Feb/2021 15:49:12] INFO [pricingsimulation.views:496] Results requested by maheshchowdary437@gmail.com at 05-02-2021 15:49:12
[05/Feb/2021 15:49:12] INFO [pricingsimulation.views:516] 72cajad57m5bgrdsib1s6z01d2abmby3:1612565352 Begin generating Result for game id: 1150
[05/Feb/2021 15:49:13] INFO [pricingsimulation.views:835] Results has been generated in 0.053546 sec for game_id: 1150
[05/Feb/2021 15:49:13] INFO [pricingsimulation.views:572] 72cajad57m5bgrdsib1s6z01d2abmby3:1612565353 Done generating results for game id: 1150 in 0.242552 ms
[05/Feb/2021 15:49:46] INFO [pricingsimulation.views:516] 72cajad57m5bgrdsib1s6z01d2abmby3:1612565386 Begin generating Result for game id: 1150
[05/Feb/2021 15:49:46] INFO [pricingsimulation.views:572] 72cajad57m5bgrdsib1s6z01d2abmby3:1612565386 Done generating results for game id: 1150 in 0.192679 ms
[05/Feb/2021 16:15:11] INFO [pricingsimulation.views:42] None:1612566911 Begin User Authentication
[05/Feb/2021 16:15:11] INFO [pricingsimulation.views:61] slkatxg4q5xmip05g5nb9vu84gsvc3uh:1612566911 End User Authentication
[05/Feb/2021 16:24:08] INFO [pricingsimulation.views:42] None:1612567448 Begin User Authentication
[05/Feb/2021 16:24:08] INFO [pricingsimulation.views:61] 8hg4tp14ykff8y08qzynbcoq7l4l5z8k:1612567448 End User Authentication
[05/Feb/2021 16:24:14] INFO [pricingsimulation.views:516] 8hg4tp14ykff8y08qzynbcoq7l4l5z8k:1612567454 Begin generating Result for game id: 1149
[05/Feb/2021 16:24:14] INFO [pricingsimulation.views:572] 8hg4tp14ykff8y08qzynbcoq7l4l5z8k:1612567454 Done generating results for game id: 1149 in 0.092002 ms
[05/Feb/2021 16:25:10] INFO [pricingsimulation.views:516] 8hg4tp14ykff8y08qzynbcoq7l4l5z8k:1612567510 Begin generating Result for game id: 1149
[05/Feb/2021 16:25:10] INFO [pricingsimulation.views:572] 8hg4tp14ykff8y08qzynbcoq7l4l5z8k:1612567510 Done generating results for game id: 1149 in 0.220575 ms
[06/Feb/2021 13:10:27] INFO [pricingsimulation.views:42] None:1612642227 Begin User Authentication
[06/Feb/2021 13:10:28] INFO [pricingsimulation.views:61] 0u8ujpqer719f8lq2kjfvxx8t1w91mxb:1612642228 End User Authentication
[06/Feb/2021 13:17:50] INFO [pricingsimulation.views:42] None:1612642670 Begin User Authentication
[06/Feb/2021 13:17:50] INFO [pricingsimulation.views:61] xwwg8phegzpdglbktek8z3a7tnrbg9bz:1612642670 End User Authentication
[06/Feb/2021 13:35:29] INFO [pricingsimulation.views:42] None:1612643729 Begin User Authentication
[06/Feb/2021 13:35:29] INFO [pricingsimulation.views:61] 9cg70qrovkr8cp6iimfiahw3ivwi9njf:1612643729 End User Authentication
[06/Feb/2021 13:37:42] INFO [pricingsimulation.views:42] None:1612643862 Begin User Authentication
[06/Feb/2021 13:37:42] INFO [pricingsimulation.views:61] s2wqtd6hvqyc1okba2fh4wjfyxpsr339:1612643862 End User Authentication
[06/Feb/2021 13:45:59] INFO [pricingsimulation.views:42] None:1612644359 Begin User Authentication
[06/Feb/2021 13:46:00] INFO [pricingsimulation.views:61] qi67ulwggvzmbuj58rs7r34i104zz0ck:1612644360 End User Authentication
[06/Feb/2021 14:14:54] INFO [pricingsimulation.views:42] None:1612646094 Begin User Authentication
[06/Feb/2021 14:14:55] INFO [pricingsimulation.views:61] oolahe8ofa4d1qv8kt210xly2wp6m0jp:1612646095 End User Authentication
